### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by ivysrono** [akof1314/Wiz.Title.Cleaner#2]
下载后双击安装，提示 安装插件文件失败。
Wiz 4.2.391
Win8.1 x64

**Comment by akof1314** [comment]
@renyouguo 直接拖曳到wiz窗口里面试试，或者用压缩软件解压到wiz的插件目录`\My Knowledge\Plugins\Wiz.Title.Cleaner`

**Comment by ivysrono** [comment]
拖拽依然失败……win7sp1 x86
反正不是必须，我就不烦解压的问题了。
装了其它四个插件，都没问题

**Comment by akof1314** [comment]
好的，我再测试测试

**Comment by akof1314** [comment]
@renyouguo 已重新上传安装包，可以再试一下
